# EEG Model Configs
eeg_encoder_model: 'cbramod'
eeg_aggregation_method: 'pooling'
eeg_encoder_dim: 200

# LLM Model Configs
llm_model: 'Qwen/Qwen3-4B-Instruct-2507'
use_chat_template: True
max_new_tokens: 2048
llm_dim: 2560
attn_implementation: 'sdpa'

# Projector Configs
projector: 'sequence_transformer_perceiver_projector'


# Training Configs
training_mode: 'projection_only'
epochs: 10 #10
batch_size: 4
gradient_accumulation_steps: 4  # Effective batch size = batch_size * gradient_accumulation_steps
learning_rate: 1e-4 #5e-4 #1e-4
max_learning_rate: 1e-3
weight_decay: 0.01
max_grad_norm: 1.0
warmup_ratio: 0.1


# Mixed precision
use_amp: True

# save configs
checkpoint_dir: 'cbramod_Qwen3-4B-Instruct-2507'
save_every_n_epochs: 1

seed: 5


# logging configs
log_dir: 'logs'
log_every_n_steps: 100
log_every_n_epochs: 1


  
  
  